adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: ${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

spring:
  kafka:
    producer:
      bootstrap-servers:
        - "localhost:9092"
        - "localhost:9094"
      client-id: "account-service"
    consumer:
      bootstrap-servers:
        - "localhost:9092"
        - "localhost:9094"
      group-id: "account-service"